# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QT51hqO3DIKzyUHV778xnD-FT4XYa_Ow
"""

def rep_char(c,n):
  print(c*n)


def draw_line_string(msg1,msg2):
  nstr = len(msg1) if (len(msg1) > len(msg2)) else len(msg2)
  rep_char('-',nstr*2+4)
  print(f'Hello {msg1:}')
  print('Welcome to Seoul.')
  rep_char('-',nstr*2+4)


  rep_char('-',nstr*2+4)
  print(f'Hello {msg2:}')
  print('Welcome to Seoul.')
  rep_char('-',nstr*2+4)


msg1= input('input his/her name: ')
msg2= input('input his/her name: ')

draw_line_string(msg1,msg2)

