# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ohPPa1y81sikOHk2eGt4tDI7X5CDrJFh
"""

def get_fixed_price(dc,p):
  dc = dc/100
  op = p / (1-dc)
  return op


dc = int(input('할인율은?'))
a_p = int(input('A 상품의 할인된 가격은?'))
b_p = int(input('B 상품의 할인된 가격은?'))

a_op  = get_fixed_price(dc,a_p)
b_op  = get_fixed_price(dc,b_p)

print('A 상품의 정가는 ',a_op,'원')
print('B 상품의 정가는 ' ,b_op, '원')