# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbwpcGN1jWbLjbb1AIog07lx2L34d07H
"""

def convert_time(m):
  fh  = m // 500
  fh1 = m%500
  h   = fh1//100
  h1  = fh1%100
  ft  = h1//50
  ft1 = h1%50
  t = ft1//10

  print('500원의 동전의 개수:',fh)
  print('100원의 동전의 개수:',h)
  print('50원의 동전의 개수:',ft)
  print('10원의 동전의 개수:',t)

def get_integer(prompt) :
 return int(input(prompt))

m =  get_integer('금액을 입력해주세요:  ')
convert_time(m)