# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGNm_DYhJ18Ak0s4AMBdVQC5FhxShbSI
"""

class Point:
    def __init__(self, x, y):
        self._x = x
        self._y = y

    def show(self):
        print(f"({self._x}, {self._y})")


class Rectangle:
    def __init__(self, x1, y1, x2, y2):
        self.lt = Point(x1, y1)
        self.rb = Point(x2, y2)

    def show(self):
        print(f"좌측 상단 꼭지점이 ({self.lt._x}, {self.lt._y})이고 우측 하단 꼭지점이 ({self.rb._x}, {self.rb._y})인 사각형입니다")

    def getWidth(self):
        return self.rb._x - self.lt._x

    def getHeight(self):
        return self.rb._y - self.lt._y

    def getArea(self):
        return self.getWidth() * self.getHeight()

    def getPerimeter(self):
        return 2 * (self.getWidth() + self.getHeight())


r1 = Rectangle(5, 5, 20, 10)
a = r1.getArea()
p = r1.getPerimeter()
r1.show()
print(f'\n넓이는 {a}, 둘레는 {p}')