# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdqjL3nPM-DCts5HDDty_sfgdCuCNUlD
"""

def read_single_digit(num):

    if num == 0:
        return "영"
    elif num == 1:
        return "일"
    elif num == 2:
        return "이"
    elif num == 3:
        return "삼"
    elif num == 4:
        return "사"
    elif num == 5:
        return "오"
    elif num == 6:
        return "육"
    elif num == 7:
        return "칠"
    elif num == 8:
        return "팔"
    elif num == 9:
        return "구"

def read_number(num):

    if num < 10:
        return read_single_digit(num)
    elif num < 100:
        t = read_single_digit(num // 10)
        o = read_single_digit(num % 10)
        return t,o

    else:
        h = read_single_digit(num // 100)
        t = read_single_digit((num // 10) % 10)
        o = read_single_digit(num % 10)
        return h,t,o



user_input = int(input("세 자리수 이하의 정수 입력: "))
read_number(user_input)
