# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEQCZ6q40HpoEtqqQfkySBzo6CxN0NhP
"""

shopping_bag = {}
while True:
  item = input('상품명 ')
  a = (input('수량은? '))
  print(f'장바구니에 {item}{a}개(가) 담겼습니다 ')
  shopping_bag[item] = a

  if item =="" or a =="":
    del shopping_bag[item]
    break

print(f'장바구니 보기 : {shopping_bag}')
print()
r = input('검색하고자 하는 상품은? ')
print(f'{r}은(는){shopping_bag[r]}개 담겨 있습니다 ')