# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18I5scuSWFBaCFGbLsJJDT9WNpvn5KgpO
"""

def ggd(start, end):
    for i in range(1, 10):
        for j in range(start, end + 1):
            result = i * j
            print(f"{j} × {i} = {result}", end="\t")
        print()

ggd(2, 5)
print()

ggd(6, 9)